title: Wintermaul Now You Lose Additional Features
description: These are additional innovative features of the hit custom game Wintermaul Now You Lose on Warcraft 3. The primary mechanics of Wintermaul Now You Lose are on my other repository not this one.
